export const MOCK_LISTINGS = [
  {
    id: 'demo_1',
    title: 'Engineering Mathematics Textbook (Kreyszig 10th Ed)',
    description: 'Very clean copy. Advanced Engineering Mathematics by Erwin Kreyszig, 10th edition. Barely used, no annotations.',
    price: 8500,
    category: 'textbooks',
    status: 'available',
    imageUrls: [],
    sellerName: 'Chidi O.',
    sellerId: 'demo',
    createdAt: null,
  },
  {
    id: 'demo_2',
    title: 'Samsung Galaxy A14 (128GB) — Excellent Condition',
    description: 'Used for 6 months. Screen protector on since day one. Comes with original charger and box.',
    price: 95000,
    category: 'electronics',
    status: 'available',
    imageUrls: [],
    sellerName: 'Amaka B.',
    sellerId: 'demo',
    createdAt: null,
  },
  {
    id: 'demo_3',
    title: 'HP Laptop 14" (Core i5, 8GB RAM, 256GB SSD)',
    description: 'Perfect for school work. Runs fast, battery lasts ~4 hours. Minor scratch on lid but screen is perfect.',
    price: 155000,
    category: 'electronics',
    status: 'available',
    imageUrls: [],
    sellerName: 'Emeka N.',
    sellerId: 'demo',
    createdAt: null,
  },
  {
    id: 'demo_4',
    title: 'Standing Fan + Desk Lamp (Bundle)',
    description: 'Both in good working condition. Selling together as a bundle since I\'m moving out of the hostel.',
    price: 12000,
    category: 'hostel_gear',
    status: 'available',
    imageUrls: [],
    sellerName: 'Funmi A.',
    sellerId: 'demo',
    createdAt: null,
  },
  {
    id: 'demo_5',
    title: 'WAEC & JAMB Past Questions Bundle (2019–2023)',
    description: '5 years of past questions with answers for Science subjects. Great for upcoming exams.',
    price: 3500,
    category: 'textbooks',
    status: 'available',
    imageUrls: [],
    sellerName: 'Tunde K.',
    sellerId: 'demo',
    createdAt: null,
  },
  {
    id: 'demo_6',
    title: 'Men\'s School Backpack (Navy Blue)',
    description: 'Used for one semester only. Laptop compartment, multiple pockets. Very spacious.',
    price: 6000,
    category: 'fashion',
    status: 'available',
    imageUrls: [],
    sellerName: 'Seun P.',
    sellerId: 'demo',
    createdAt: null,
  },
];
